title: automation for performance of Alvin Lucier's 'I Am Sitting in a Room'
start:
  year: 2024
  month: 3
slug: i-am-sitting-in-a-room-by-alvin-lucier
tags:
  - code:matlab
  - code:lua
  - topic:sound
