title: advent of code
slug: advent-of-code
start:
  year: 2021
links:
  - name: 2021
    url: https://github.com/nj-vs-vh/advent-of-code-2021
  - name: 2022
    url: https://github.com/nj-vs-vh/advent-of-code-2022
  - name: 2023
    url: https://github.com/nj-vs-vh/advent-of-code-2023
