title: matrix legend for Matplotlib
start:
  year: 2025
  month: 9
slug: matrix-legend
github: https://github.com/nj-vs-vh/matplotlib-matrix-legend
tags:
  - code:python
  - platform:library
  - topic:science
  - topic:visualization
