title: browser version of cosmic rays spectrum plot
start:
  year: 2024
  month: 1
github: https://github.com/nj-vs-vh/The_CR_Spectrum
links:
  - name: original plot repo
    url: https://github.com/carmeloevoli/The_CR_Spectrum
