title: browser version of cosmic rays spectrum plot
slug: crspectrum-plot-web-version
start:
  year: 2024
  month: 1
github: https://github.com/nj-vs-vh/The_CR_Spectrum
links:
  - name: plot
    url: https://cosmic-rays-spectrum.nj-vs-vh.name/
  - name: upstream plot repo
    url: https://github.com/carmeloevoli/The_CR_Spectrum
