title: semantle in russian
start:
  year: 2022
  month: 6
slug: ru-semantle
github: https://github.com/nj-vs-vh/ru-semantle
links:
  - name: play (in russian)
    url: https://ru-semantle.nj-vs-vh.name/
