title: semantle clone in russian
start:
  year: 2022
  month: 6
slug: ru-semantle
github: https://github.com/nj-vs-vh/ru-semantle
links:
  - name: play
    url: https://ru-semantle.nj-vs-vh.name/
tags:
  - code:python
  - code:svelte
  - platform:web

