title: slow-learner, python type inference tool
start:
  year: 2022
  month: 11
slug: slow-learner
github: https://github.com/nj-vs-vh/slow-learner
links:
  - name: PyPI
    url: https://pypi.org/project/slow-learner
code_languages:
  - python
tags:
  - code:python
  - platform:library
  