title: "Friendship with cybergolem: political history of AI - an essay"
start:
  year: 2026
  month: 1
slug: against-ai
links:
  - name: publication (in russian)
    url: https://doxa.team/articles/cybergolem
tags:
  - platform:essay
  - topic:ai
