title: chord finder, a minimalist computer music generator
start:
  year: 2024
  month: 4
slug: chord-finder
github: https://github.com/nj-vs-vh/chord-finder
links:
  - name: chord-finder
    url: https://chord-finder.nj-vs-vh.name/
math: true
tags:
  - code:js
  - topic:sound
  - platform:web
