title: Daf Yomi bot
start:
  year: 2024
  month: 11
slug: daf-yomi-bot
github: https://github.com/nj-vs-vh/daf-yomi-bot
links:
  - name: telegram channel
    url: https://t.me/daf_yomi_text
math: false
tags:
  - code:python
  - platform:telegram
