title: pyindigo, python interface for INDIGO astronomy software framework
start:
  year: 2020
  month: 10
slug: pyindigo
github: https://github.com/nj-vs-vh/pyindigo
tags:
  - code:python
  - code:c
  - platform:library
  - topic:science

