title: solar system disruption simulation
slug: solar-system-disruption-bot
github: https://github.com/nj-vs-vh/solar-system-disruption-bot
links:
  - name: telegram channel
    url: https://t.me/solar_system_disruption
