title: Tanakh website
start:
  year: 2022
  month: 11
slug: tanakh-reading
github: https://github.com/nj-vs-vh/tanakh-reading
links:
  - name: website
    url: https://tanakh-reading.nj-vs-vh.name/
  